from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
SUPP = ROOT
DATA = SUPP / "data"
FIGS = SUPP / "figures"


def main() -> None:
    DATA.mkdir(parents=True, exist_ok=True)
    FIGS.mkdir(parents=True, exist_ok=True)

    vscale = pd.DataFrame(
        [
            ["V0", "internal algebraic consistency", "limits, units, monotonicity, extreme cases", "met; limiting cases and bounded decomposition retained"],
            ["V1", "numerical verification", "Monte Carlo convergence, FOSM comparison, seed-controlled scripts", "met; MC/FOSM and convergence files available"],
            ["V2", "independent model comparison", "limit analysis, FEM/DEM, different implementation", "met for screening; open-source limit analysis, OpenSeesPy, and CalculiX audits"],
            ["V3", "experimental component validation", "plate/load-settlement, UCS, triaxial, UPV/Vs, durability retention", "met at component level using published datasets"],
            ["V4", "coupled indirect validation", "experimental components + virtual degraded footing + hold-out/falsification", "target status; V4-level architecture, not direct footing validation"],
            ["V5", "direct physical degraded-footing validation", "plate/footing test on degraded MICP-treated sand", "not claimed; no accessible direct degraded-footing test located"],
            ["V6", "field-scale validation", "field footing/plate with service-life exposure", "not claimed"],
        ],
        columns=["level", "meaning", "evidence_required", "manuscript_status"],
    )
    vscale.to_csv(DATA / "v4_validation_scale_v0_v6.csv", index=False)

    inventory = pd.DataFrame(
        [
            [
                "Kulkarni et al. (2021)",
                "https://pdfs.semanticscholar.org/b683/b7a6dc2f6af56304e9a278200718f1c5ca83.pdf",
                "plate-load/load-settlement and UCS/permeability",
                "laboratory plate",
                "qu, settlement, BCR, SRF, UCS",
                "digitized square 120 mm curve and table summaries",
                "eta0, stiffness/service curve, initial bearing response",
                "calibration and held-out response check",
                "V3",
            ],
            [
                "Sharma et al. (2021)",
                "https://www.sciencedirect.com/science/article/pii/S0016706121004390",
                "durability retention under wetting-drying and ageing",
                "element/cylindrical specimens",
                "UPV, shear modulus, UCS, STS, mass loss",
                "digitized retention at 0, 5, 10, 15, 20 cycles",
                "lambda_e, eta_r, degradation-law selection",
                "early-cycle calibration and late-cycle hold-out",
                "V3",
            ],
            [
                "Rezende et al. (2022)",
                "https://link.springer.com/article/10.1007/s10706-021-02006-4",
                "triaxial strength and stiffness",
                "element/triaxial",
                "deviator stress, confining pressure, cohesion intercept",
                "reported cohesion increase to about 75 kPa; figure data require verification",
                "cb0_prime, Delta tan phi split, anti-double-counting bounds",
                "calibration constraint; requires verification for curve digitization",
                "V3",
            ],
            [
                "Open-source limit analysis benchmark",
                "local supplement",
                "independent numerical mechanism",
                "virtual footing",
                "qu vs H/B",
                "CSV generated by open-source limit-analysis script",
                "thin-layer capping and H/B domain",
                "V2 mechanistic audit and M8 input",
                "V2-V4",
            ],
            [
                "OpenSeesPy and CalculiX audits",
                "local supplement",
                "independent FEM/serviceability checks",
                "virtual footing",
                "normalized capacity/stiffness/settlement trends",
                "CSV generated by independent FEM scripts",
                "virtual degraded-footing trend, stiffness cap",
                "M8 coupled virtual-footing evidence",
                "V2-V4",
            ],
        ],
        columns=[
            "source",
            "doi_or_url",
            "data_type",
            "scale",
            "measured_variable",
            "extractable_data",
            "parameter_informed",
            "use",
            "v_level",
        ],
    )
    inventory.to_csv(DATA / "v4_component_dataset_inventory.csv", index=False)

    partition = pd.DataFrame(
        [
            ["initial strength", "Kulkarni square PLT early/pre-ultimate branch; Rezende triaxial bounds", "eta0, cb0_prime, Delta tan phi", "Kulkarni held-out ultimate/table response or treatment contrast", "qu/SRF/BCR range check", "composite strength may confound cohesion and friction"],
            ["degradation", "Sharma 0-10 wetting-drying cycles", "lambda_e, eta_r, degradation law", "Sharma 15-20 cycles", "late-cycle MAPE and law ranking", "single exponential may underpredict late damage"],
            ["service response", "untreated and treated pre-ultimate q-s branch", "hyperbolic/secant stiffness", "larger settlement branch or alternative plate geometry", "NRMSE/MAPE of q-s curve", "open PDF limits individual circular-plate curves"],
            ["treated depth", "H/B=1.0 and 1.5 virtual audits", "kH, chi_s, cap factor", "H/B=0.5 and 2.0", "monotonicity and capped error", "thin treated crusts require capping"],
            ["global M8 model", "all component-calibrated parameters fixed before virtual-footing run", "no post-hoc global tuning", "coupled degraded-footing response", "Eq. vs capped vs FEM/limit error", "V4 only; not physical V5 validation"],
        ],
        columns=["dataset_block", "calibration_data", "parameters_calibrated", "reserved_data", "holdout_test", "risk"],
    )
    partition.to_csv(DATA / "v4_calibration_holdout_partition.csv", index=False)

    comparison = pd.DataFrame(
        [
            ["limit/FEM audit", 0.5, 50, "virtual FEM/limit", 23.0, 11.0, "cap mandatory"],
            ["limit/FEM audit", 1.0, 50, "virtual FEM/limit", 19.7, 10.5, "cap recommended"],
            ["limit/FEM audit", 1.5, 50, "virtual FEM/limit", 11.8, 8.4, "screening acceptable with cap"],
            ["limit/FEM audit", 2.0, 50, "virtual FEM/limit", 5.7, 5.7, "closed form acceptable for screening"],
            ["serviceability audit", 2.0, 50, "CalculiX elastic 3D", 0.0, 0.0, "service trend only; not collapse validation"],
        ],
        columns=["case", "H_over_B", "time_or_exposure", "reference", "closed_form_error_percent", "capped_error_percent", "decision"],
    )
    comparison.to_csv(DATA / "v4_closed_form_capped_fem_comparison.csv", index=False)

    m8 = pd.DataFrame(
        [
            ["M0", "untreated no MICP credit", "baseline inputs", "untreated reference", "", 0.26, 0.397, "", "fails beta target"],
            ["M1", "permanent MICP credit", "initial component response only", "non-degrading response", "", 2.62, 0.0044, "", "over-credit risk"],
            ["M3/M4", "degrading closed-form models", "durability-calibrated degradation", "time-dependent reliability", "model-form spread", 1.13, 0.129, "", "fails beta target"],
            ["M7", "degrading model with H/B cap", "FEM/limit audit plus degradation", "capped time-dependent reliability", "thin-layer conservative", 0.60, 0.273, "", "fails beta target"],
            ["M8", "V4 coupled virtual-footing model constrained by component datasets", "component-calibrated strength, service, degradation; independent FEM/limit trend", "degraded-footing response with no global retuning", "screening if capped error <=15%; otherwise FEM recalibration", 1.38, 0.086, 576, "V4 support, not V5; qservice=900 fails"],
        ],
        columns=["model", "description", "data_used", "prediction", "external_error_summary", "beta50", "pf50", "qservice_max_kPa", "decision"],
    )
    m8.to_csv(DATA / "v4_model_m0_m8_comparison.csv", index=False)

    falsification = pd.DataFrame(
        [
            ["retention law", "selected law cannot predict hold-out", "hold-out MAPE <20-25%", "use Weibull/bilinear and update posterior"],
            ["capacity", "closed form overpredicts >25%", "capped error <15%", "make capping mandatory or require FEM"],
            ["service", "q-s trend not reproduced", "NRMSE <0.25 for pre-ultimate branch", "replace sI with calibrated q-s curve"],
            ["H/B trend", "FEM/limit trend contradicts closed form", "monotonic/capped trend consistent", "recalibrate kH and chi_s"],
            ["rival model", "fixed reduction M2 matches M3/M7 decisions", "degradation changes critical decision", "simplify or justify dynamic coupling"],
            ["uncertainty", "posteriors do not discriminate designs", "beta thresholds separate safe/unsafe region", "declare non-identifiability"],
        ],
        columns=["test", "weakens_model_if", "strengthens_model_if", "action_if_failed"],
    )
    falsification.to_csv(DATA / "v4_acceptance_falsification_criteria.csv", index=False)

    fig, ax = plt.subplots(figsize=(8.2, 4.7), dpi=180)
    ax.axis("off")
    boxes = [
        (0.03, 0.68, "Experimental\ncomponents\nPLT, UCS,\ntriaxial, UPV"),
        (0.25, 0.68, "Separate\ncalibration\nstrength,\nstiffness,\ndegradation"),
        (0.47, 0.68, "Frozen\nparameters\nno global\nretuning"),
        (0.69, 0.68, "Virtual degraded\nfooting\nFEM/limit\nH/B,t"),
        (0.25, 0.22, "Hold-out\nlate cycles,\nreserved q-s,\nH/B cases"),
        (0.47, 0.22, "Falsification\nerror bands,\ncapping,\ndomain limits"),
        (0.69, 0.22, "Reliability\nbeta(t), pf(t),\nqservice,max"),
    ]
    for x, y, text in boxes:
        ax.add_patch(plt.Rectangle((x, y), 0.17, 0.20, fc="#eef3f7", ec="#333333", lw=1.0))
        ax.text(x + 0.085, y + 0.10, text, ha="center", va="center", fontsize=7.3)
    arrows = [
        ((0.20, 0.78), (0.25, 0.78)),
        ((0.42, 0.78), (0.47, 0.78)),
        ((0.64, 0.78), (0.69, 0.78)),
        ((0.335, 0.68), (0.335, 0.42)),
        ((0.555, 0.68), (0.555, 0.42)),
        ((0.775, 0.68), (0.775, 0.42)),
        ((0.42, 0.32), (0.47, 0.32)),
        ((0.64, 0.32), (0.69, 0.32)),
    ]
    for start, end in arrows:
        ax.annotate("", xy=end, xytext=start, arrowprops=dict(arrowstyle="->", color="#333333", lw=1.0))
    ax.text(0.50, 0.06, "V4-level coupled virtual-footing validation; not V5 direct degraded-footing validation", ha="center", fontsize=8.2)
    fig.tight_layout()
    fig.savefig(FIGS / "figure_v4_validation_architecture.png")
    fig.savefig(FIGS / "figure_v4_validation_architecture.svg")
    plt.close(fig)

    print(DATA / "v4_model_m0_m8_comparison.csv")


if __name__ == "__main__":
    main()
